# Generated by Django 4.2.5 on 2023-10-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tax Type(out space)'),
        ),
    ]
